### ISSUE TITLE
module partly broken, bummer

### ISSUE THREAD

**Issue by rhodey** [rhodey/hyper-storage-minio#1]
I have not been a JS programmer for very long and I do not understand what I am doing with classes and inheritance and so while the official(?) [random-access-test suite](https://github.com/random-access-storage/random-access-test) passes you will see in file `test.bummer.js` or by running `npm run bummer` that for some reason this module does not play nicely with hypercore.

I have to say the whole `random-access-storage` interface is brilliant but figuring out exactly what methods to implement and how has been a struggle. `random-access-memory` and `random-access-file` for example behave very similarly but due to their nature must implement some methods a little differently.

I will try to wrangle this bug once more this weekend... beat me to it?? :pray:

**Comment by rhodey** [comment]
```
rhodey@lolqut:~/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio$ npm run bummer

> hyper-storage-minio@0.0.1 bummer /home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio
> node test.bummer.js

/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/test.bummer.js:22
  if (err) throw err
           ^

Error: Not opened
    at Request._openAndNotClosed (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:168:53)
    at Request._run (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:196:16)
    at RandomWithWriteDestroyCb.RandomAccess.run (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:100:12)
    at RandomWithWriteDestroyCb.RandomAccess.write (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:53:8)
    at PartWithWriteOnce._write (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/index.js:158:18)
    at Request._run (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:196:40)
    at PartWithWriteOnce.RandomAccess.run (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:100:12)
    at PartWithWriteOnce.RandomAccess.write (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/random-access-storage/index.js:53:8)
    at /home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/multi-random-access/index.js:75:21
    at Storage._getOrCreate (/home/rhodey/dev/dsp/radiowitness.dat/lib/js/hyper-storage-minio/node_modules/multi-random-access/index.js:303:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hyper-storage-minio@0.0.1 bummer: `node test.bummer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hyper-storage-minio@0.0.1 bummer script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rhodey/.npm/_logs/2020-01-30T02_17_03_515Z-debug.log
```

**Comment by rhodey** [comment]
## RELEVANT
this module depends on changes within my multi-random-access and random-access-pause-wrapper clones see:

https://github.com/rhodey/multi-random-access

and

https://github.com/rhodey/random-access-pause-wrapper
